version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cs308-mysql
    restart: always
    environment:
      MYSQL_DATABASE: cs308db
      MYSQL_USER: cs308user
      MYSQL_PASSWORD: cs308pass
      MYSQL_ROOT_PASSWORD: rootpass
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: 