# Generated by Django 5.2.1 on 2025-05-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_manager_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_address',
            field=models.CharField(default='Default Address', max_length=255),
        ),
    ]
