# Generated by Django 5.2.1 on 2025-05-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('sales_manager', 'Sales Manager'), ('product_manager', 'Product Manager')], default='customer', max_length=20),
        ),
    ]
