# Generated by Django 5.2.1 on 2025-05-23 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_delivery_address'),
        ('products', '0002_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number_hash', models.CharField(max_length=64)),
                ('card_number_salt', models.CharField(max_length=32)),
                ('cvv_hash', models.CharField(max_length=64)),
                ('cvv_salt', models.CharField(max_length=32)),
                ('expiry_date', models.CharField(max_length=5)),
                ('card_holder_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='accounts.user')),
            ],
        ),
    ]
