# Generated by Django 5.1.5 on 2025-04-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
