# Generated by Django 5.1.7 on 2025-05-20 21:56

from django.db import migrations

def set_priced(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    # Fiyatı 0’dan büyük olan tüm ürünleri is_priced=True yap
    Product.objects.filter(price__gt=0).update(is_priced=True)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_cost_price_product_discount_rate_and_more'),
    ]

    operations = [
        #migrations.RunPython(set_priced, migrations.RunPython.noop),
    ]
